service: serverless-crud-python-demo

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}

plugins:
  - serverless-python-requirements
  - serverless-offline

functions:
  createItem:
    handler: src/handlers/items.create
    events:
      - http:
          path: /items
          method: post
          cors: true
          private: true

  getItem:
    handler: src/handlers/items.get
    events:
      - http:
          path: /items/{id}
          method: get
          cors: true
          private: true

  listItems:
    handler: src/handlers/items.list_items
    events:
      - http:
          path: /items
          method: get
          cors: true
          private: true

  updateItem:
    handler: src/handlers/items.update
    events:
      - http:
          path: /items/{id}
          method: put
          cors: true
          private: true

  deleteItem:
    handler: src/handlers/items.delete
    events:
      - http:
          path: /items/{id}
          method: delete
          cors: true
          private: true

custom:
  pythonRequirements:
    dockerizePip: false
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0
    apiKey: false  # Tắt kiểm tra API key khi chạy local
